from collections.abc import Iterable
from typing import Generic, TypeVar

T = TypeVar("T")


class MinHeap(Generic[T]):
    def __init__(self, items: Iterable[T] | None = None): ...
    def push(self, item: T) -> None: ...
    def pop(self) -> T: ...
    def peek(self) -> T: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
